# Generated by Django 3.2 on 2022-07-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_welcomemessage_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WelcomeMessage',
        ),
    ]
